from app.services.similarity import get_similarity_scores

def calculate_trust_score(answer: str, retrieved_chunks: list[dict]) -> dict:
    """
    Evaluates whether the generated answer is supported by the retrieved document chunks.
    Calculates a trust score (0-100), maps a risk level, and generates warnings.
    
    Args:
        answer (str): The text answer generated by the LLM.
        retrieved_chunks (list[dict]): The chunks retrieved from the vector store.
        
    Returns:
        dict: A dictionary containing the trust_score, risk_level, retrieval_strength,
              citation_support, and warnings.
    """
    refusal_text = "I could not find enough evidence in the uploaded documents."
    
    # 1. Handle empty answer
    if not answer or not answer.strip():
        return {
            "trust_score": 0,
            "risk_level": "High",
            "retrieval_strength": "None",
            "citation_support": "None (Answer is empty)",
            "warnings": ["Generated answer is empty."]
        }
        
    # 2. Handle correct refusal to answer
    # If the LLM correctly refuses to answer because there's no evidence,
    # the hallucination risk is Low, although the trust_score is set to a baseline.
    if refusal_text.lower() in answer.lower():
        return {
            "trust_score": 50,  # Baseline score for proper refusal (no facts stated to doubt)
            "risk_level": "Low",  # Low risk because the model didn't make anything up
            "retrieval_strength": "N/A",
            "citation_support": "None (Model correctly declined to answer due to insufficient context)",
            "warnings": []
        }
        
    # 3. Handle empty retrieval context
    if not retrieved_chunks:
        return {
            "trust_score": 0,
            "risk_level": "High",
            "retrieval_strength": "None",
            "citation_support": "None (No context retrieved)",
            "warnings": ["No context chunks were retrieved to verify the answer. High risk of hallucination."]
        }
        
    # 4. Extract text from retrieved chunks and compute similarity scores
    chunk_texts = [chunk["text"] for chunk in retrieved_chunks]
    sim_scores = get_similarity_scores(answer, chunk_texts)
    
    max_sim = max(sim_scores) if sim_scores else 0.0
    
    # Analyze the retrieval query similarity (ChromaDB relevance scores)
    retrieval_scores = [chunk.get("similarity_score", 0.0) for chunk in retrieved_chunks]
    max_retrieval = max(retrieval_scores) if retrieval_scores else 0.0
    avg_retrieval = sum(retrieval_scores) / len(retrieval_scores) if retrieval_scores else 0.0
    
    # 5. Base trust score calculation (0 - 100)
    # 5. Base trust score calculation (0 - 100)
    # Map raw cosine similarity to 0-100 scale using a realistic range for sentence embeddings.
    # Typically, similarity >= 0.6 is a near-perfect match, and similarity <= 0.15 is irrelevant.
    if max_sim <= 0.15:
        base_score = 0
    else:
        base_score = int(((max_sim - 0.15) / 0.45) * 100)
    base_score = max(0, min(100, base_score))
    
    # 6. Apply support boosts
    # Boost the score slightly if multiple independent chunks corroborate the answer (similarity >= 0.5)
    corroborating_chunks = sum(1 for score in sim_scores if score >= 0.5)
    boost = 0
    if corroborating_chunks > 1:
        # Boost up to 10 points for multiple supporting chunks
        boost = min(10, (corroborating_chunks - 1) * 3)
        
    # 7. Keyword validation (detecting terms in answer not present in any chunk)
    stopwords = {
        'the', 'a', 'an', 'and', 'or', 'but', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
        'have', 'has', 'had', 'do', 'does', 'did', 'to', 'of', 'in', 'for', 'on', 'with', 'at', 'by',
        'from', 'about', 'as', 'into', 'through', 'during', 'before', 'after', 'above', 'below',
        'up', 'down', 'out', 'off', 'over', 'under', 'again', 'further', 'then', 'once',
        'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more',
        'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than',
        'too', 'very', 'can', 'will', 'just', 'should', 'now', 'it', 'its', 'they', 'them', 'their',
        'theirs', 'this', 'that', 'these', 'those', 'who', 'whom', 'which', 'what', 'i', 'you', 'he',
        'she', 'we', 'us', 'me', 'him', 'her'
    }
    
    warnings = []
    
    import re
    def get_clean_words(text: str) -> set[str]:
        words = re.findall(r'\b\w+\b', text.lower())
        return {w for w in words if w not in stopwords and not w.isdigit()}
        
    answer_words = get_clean_words(answer)
    chunk_words = set()
    for chunk in retrieved_chunks:
        chunk_words.update(get_clean_words(chunk["text"]))
        
    unsupported_words = sorted(list(answer_words - chunk_words))
    
    penalty = 0
    if unsupported_words:
        # Penalty of 15 points per unsupported word, capped at 60 points
        penalty = min(60, len(unsupported_words) * 15)
        warnings.append(f"The answer contains terms not found in the source documents: {', '.join(unsupported_words)}.")
        
    # Calculate final trust score by applying boost and penalty
    trust_score = max(0, min(100, base_score + boost - penalty))
    
    # 8. Determine risk level, citations support, and build warnings
    if trust_score >= 70:
        risk_level = "Low"
        citation_support = "Strong support (Answer is backed by matching source passages)"
    elif trust_score >= 40:
        risk_level = "Medium"
        citation_support = "Moderate support (Answer aligns with parts of the source text)"
        warnings.append("The answer is only partially supported by retrieved chunks.")
    else:
        risk_level = "High"
        citation_support = "Weak support (Answer lacks significant matches in source documents)"
        if not unsupported_words:
            warnings.append("High risk of hallucination: generated answer diverges from source text.")
            
    # Additional warnings based on retrieval quality
    if max_retrieval < 0.4:
        warnings.append("Retrieval relevance is low; the retrieved chunks may not match the query.")
        
    retrieval_strength = f"Max: {max_retrieval:.2f}, Avg: {avg_retrieval:.2f}"
    
    return {
        "trust_score": trust_score,
        "risk_level": risk_level,
        "retrieval_strength": retrieval_strength,
        "citation_support": citation_support,
        "warnings": warnings
    }
